version: '3.9'

services:
  beego:
    container_name: apibeego
    image: apibeego/dm:1.0
    build: .
    ports:
      - "9333:9333"
    environment:
      ConnectionStrings__DefaultConnection: "Host=dbApibeego;Database=postgres;Username=postgres;Password=postgres"
    depends_on:
      - "dbApibeego"
  dbApibeego:
    container_name: dbApibeego
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./seeds/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: {}